added mayhem support
mayhemheroes/pyWhat pull request #1
Opened 2023-01-27 23:38 UTC by matl4c

2023-02-10 05:14 UTC, xansec requested changes
Could you please restore the deleted workflow? Please make the requested changes.

2023-02-14 22:56 UTC, matl4c commented
changed completed

2023-02-28 19:49 UTC, xansec requested changes
Please make the requested changes.

2023-02-28 19:49 UTC, xansec commented on mayhem/fuzz-pywhat.py
> +#! /usr/bin/python3
One more thing as I'm looking at this - I don't think using `sys.maxsize` is a good idea here, as there's no guarantee on the length of the fuzzed data (could be smaller). Can you instead use `fdp.remainingBytes()` here?

2023-03-05 16:18 UTC, matl4c commented on mayhem/fuzz-pywhat.py
> +#! /usr/bin/python3
change completed

2023-03-05 20:45 UTC, xansec approved these changes
LGTM!

2023-03-05 20:45 UTC, merged

2023-03-06 15:29 UTC, xansec commented
@matl4c This appears to not work:

```
 === Uncaught Python exception: ===
AttributeError: 'atheris.native.FuzzedDataProvider' object has no attribute 'remainingBytes'
Traceback (most recent call last):
  File "/src/./mayhem/fuzz-pywhat.py", line 12, in TestOneInput
    data = fdp.remainingBytes()
```

The following commit resolves
https://github.com/mayhemheroes/pyWhat/commit/a78ca10e9ef3f5ff3550662d52f01c68986e30c9

2023-03-07 16:00 UTC, matl4c commented
> @matl4c This appears to not work:
> 
> ```
>  === Uncaught Python exception: ===
> AttributeError: 'atheris.native.FuzzedDataProvider' object has no attribute 'remainingBytes'
> Traceback (most recent call last):
>   File "/src/./mayhem/fuzz-pywhat.py", line 12, in TestOneInput
>     data = fdp.remainingBytes()
> ```
> 
> The following commit resolves [a78ca10](https://github.com/mayhemheroes/pyWhat/commit/a78ca10e9ef3f5ff3550662d52f01c68986e30c9)

Sorry, I will test better in the future, thank you for the fix. Is there anything else you need from me on this one?

2023-03-07 16:46 UTC, xansec commented
No, that's it for now.